language: java
jdk: oraclejdk8

install: true
script: mvn install

after_success:
  - pwd
  - mkdir $HOME/buildApk/
  - ls -l
  - cd $HOME/buildApk/
  - ls -l
  - git config --global user.email "yasmine.mhiri96@gmail.com"
  - git config --global user.name "YasmineMh"
  - git clone --depth=50 --branch=master  https://github.com/YasmineMh/Spring-Security-.git
  - cd Spring-Security-
  - ls -l
  - cp -r /home/travis/build/YasmineMh/Spring-Security-/target $HOME/buildApk/SpringSecurity
  - ls -l 
  - git add -f
  - git remote rm origin
  - git remote add origin https://graphis:$GITHUB_API_KEY@githun.com/YasmineMh/Spring-Security-.git
  - git add -f
  - git commit -m "Yasmine build $TRAVIS_BUILD_NUMBER pushed"
  - git push -fq origin master
  - echo -e "DONE!"